# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\keypg\Documents\Coding\Python\ElevatorSimulator\ElevatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import importlib.util
spec = importlib.util.spec_from_file_location("GraphCanvas", "bin/GraphCanvas.py")
impCanvas = importlib.util.module_from_spec(spec)
spec.loader.exec_module(impCanvas)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.simulateArea = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.simulateArea.setContentsMargins(0, 0, 0, 0)
        self.simulateArea.setObjectName("simulateArea")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.simulateArea.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(420, 10, 371, 421))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.graphArea = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.graphArea.setContentsMargins(0, 0, 0, 0)
        self.graphArea.setObjectName("graphArea")
        self.labelForPopulationTable = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelForPopulationTable.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForPopulationTable.setObjectName("labelForPopulationTable")
        self.graphArea.addWidget(self.labelForPopulationTable, 1, 0, 1, 1)
        self.graphCanvas = impCanvas.GraphCanvas(self.gridLayoutWidget_2, width = 8, height = 8)
        self.graphArea.addWidget(self.graphCanvas, 0, 0, 1, 1)
        self.populationTable = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.populationTable.setObjectName("populationTable")
        self.populationTable.setColumnCount(3)
        self.populationTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.populationTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(1, 2, item)
        self.graphArea.addWidget(self.populationTable, 2, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 440, 401, 201))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.assignArea = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.assignArea.setContentsMargins(0, 0, 0, 0)
        self.assignArea.setObjectName("assignArea")
        self.nFloor = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.nFloor.setObjectName("nFloor")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.assignArea.addWidget(self.nFloor, 2, 0, 1, 1)
        self.labelForAdvance = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForAdvance.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelForAdvance.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForAdvance.setObjectName("labelForAdvance")
        self.assignArea.addWidget(self.labelForAdvance, 0, 1, 1, 1)
        self.labelForElevator = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForElevator.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForElevator.setObjectName("labelForElevator")
        self.assignArea.addWidget(self.labelForElevator, 3, 0, 1, 1)
        self.nElevator = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.nElevator.setObjectName("nElevator")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.assignArea.addWidget(self.nElevator, 4, 0, 1, 1)
        self.nDinning = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.nDinning.setObjectName("nDinning")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.assignArea.addWidget(self.nDinning, 6, 0, 1, 1)
        self.labelForLambda1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForLambda1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForLambda1.setObjectName("labelForLambda1")
        self.assignArea.addWidget(self.labelForLambda1, 3, 1, 1, 1)
        self.labelForMaximum = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForMaximum.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForMaximum.setObjectName("labelForMaximum")
        self.assignArea.addWidget(self.labelForMaximum, 1, 1, 1, 1)
        self.labelForNumber = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForNumber.setObjectName("labelForNumber")
        self.assignArea.addWidget(self.labelForNumber, 0, 0, 1, 1)
        self.labelForFloor = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForFloor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForFloor.setObjectName("labelForFloor")
        self.assignArea.addWidget(self.labelForFloor, 1, 0, 1, 1)
        self.labelForDinning = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelForDinning.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForDinning.setObjectName("labelForDinning")
        self.assignArea.addWidget(self.labelForDinning, 5, 0, 1, 1)
        self.lebelForLambda2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lebelForLambda2.setAlignment(QtCore.Qt.AlignCenter)
        self.lebelForLambda2.setObjectName("lebelForLambda2")
        self.assignArea.addWidget(self.lebelForLambda2, 5, 1, 1, 1)
        self.lineEditMaxPopulation = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditMaxPopulation.setObjectName("lineEditMaxPopulation")
        self.assignArea.addWidget(self.lineEditMaxPopulation, 2, 1, 1, 1)
        self.lineEditLambda1 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditLambda1.setObjectName("lineEditLambda1")
        self.assignArea.addWidget(self.lineEditLambda1, 4, 1, 1, 1)
        self.lineEditLambda2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEditLambda2.setObjectName("lineEditLambda2")
        self.assignArea.addWidget(self.lineEditLambda2, 6, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(420, 440, 371, 201))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.controlArea = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.controlArea.setContentsMargins(0, 0, 0, 0)
        self.controlArea.setObjectName("controlArea")
        self.labelForSpeedSlider = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelForSpeedSlider.setAlignment(QtCore.Qt.AlignCenter)
        self.labelForSpeedSlider.setObjectName("labelForSpeedSlider")
        self.controlArea.addWidget(self.labelForSpeedSlider, 1, 0, 1, 1)
        self.stopBtn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.stopBtn.setObjectName("stopBtn")
        self.controlArea.addWidget(self.stopBtn, 2, 2, 1, 1)
        self.startBtn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.startBtn.setObjectName("startBtn")
        self.controlArea.addWidget(self.startBtn, 2, 0, 1, 1)
        self.pauseBtn = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pauseBtn.setObjectName("pauseBtn")
        self.controlArea.addWidget(self.pauseBtn, 2, 1, 1, 1)
        self.speedSlider = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName("speedSlider")
        self.controlArea.addWidget(self.speedSlider, 1, 1, 1, 1)
        self.timer = QtWidgets.QTimeEdit(self.gridLayoutWidget_4)
        self.timer.setEnabled(True)
        self.timer.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.timer.setWrapping(False)
        self.timer.setFrame(False)
        self.timer.setAlignment(QtCore.Qt.AlignCenter)
        self.timer.setReadOnly(False)
        self.timer.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timer.setAccelerated(False)
        self.timer.setObjectName("timer")
        self.controlArea.addWidget(self.timer, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ElevatorSimulator"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Elevator 1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Elevator 2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Elevator 3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Up,Down"))
        self.labelForPopulationTable.setText(_translate("MainWindow", "Population in each floor"))
        item = self.populationTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Floor"))
        item = self.populationTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Population"))
        item = self.populationTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lambda"))
        __sortingEnabled = self.populationTable.isSortingEnabled()
        self.populationTable.setSortingEnabled(False)
        item = self.populationTable.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.populationTable.item(0, 1)
        item.setText(_translate("MainWindow", "11"))
        item = self.populationTable.item(0, 2)
        item.setText(_translate("MainWindow", "4"))
        item = self.populationTable.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.populationTable.item(1, 1)
        item.setText(_translate("MainWindow", "43"))
        item = self.populationTable.item(1, 2)
        item.setText(_translate("MainWindow", "8"))
        self.populationTable.setSortingEnabled(__sortingEnabled)
        self.nFloor.setItemText(0, _translate("MainWindow", "5"))
        self.nFloor.setItemText(1, _translate("MainWindow", "6"))
        self.nFloor.setItemText(2, _translate("MainWindow", "7"))
        self.nFloor.setItemText(3, _translate("MainWindow", "8"))
        self.nFloor.setItemText(4, _translate("MainWindow", "9"))
        self.nFloor.setItemText(5, _translate("MainWindow", "10"))
        self.nFloor.setItemText(6, _translate("MainWindow", "11"))
        self.nFloor.setItemText(7, _translate("MainWindow", "12"))
        self.nFloor.setItemText(8, _translate("MainWindow", "13"))
        self.nFloor.setItemText(9, _translate("MainWindow", "14"))
        self.nFloor.setItemText(10, _translate("MainWindow", "15"))
        self.nFloor.setItemText(11, _translate("MainWindow", "16"))
        self.nFloor.setItemText(12, _translate("MainWindow", "17"))
        self.nFloor.setItemText(13, _translate("MainWindow", "18"))
        self.nFloor.setItemText(14, _translate("MainWindow", "19"))
        self.nFloor.setItemText(15, _translate("MainWindow", "20"))
        self.nFloor.setItemText(16, _translate("MainWindow", "21"))
        self.nFloor.setItemText(17, _translate("MainWindow", "22"))
        self.nFloor.setItemText(18, _translate("MainWindow", "23"))
        self.nFloor.setItemText(19, _translate("MainWindow", "24"))
        self.nFloor.setItemText(20, _translate("MainWindow", "25"))
        self.nFloor.setItemText(21, _translate("MainWindow", "26"))
        self.nFloor.setItemText(22, _translate("MainWindow", "27"))
        self.nFloor.setItemText(23, _translate("MainWindow", "28"))
        self.nFloor.setItemText(24, _translate("MainWindow", "29"))
        self.nFloor.setItemText(25, _translate("MainWindow", "30"))
        self.labelForAdvance.setText(_translate("MainWindow", "Advance settings"))
        self.labelForElevator.setText(_translate("MainWindow", "Elevator"))
        self.nElevator.setItemText(0, _translate("MainWindow", "2"))
        self.nElevator.setItemText(1, _translate("MainWindow", "3"))
        self.nElevator.setItemText(2, _translate("MainWindow", "4"))
        self.nElevator.setItemText(3, _translate("MainWindow", "5"))
        self.nElevator.setItemText(4, _translate("MainWindow", "6"))
        self.nDinning.setItemText(0, _translate("MainWindow", "1"))
        self.nDinning.setItemText(1, _translate("MainWindow", "2"))
        self.nDinning.setItemText(2, _translate("MainWindow", "3"))
        self.nDinning.setItemText(3, _translate("MainWindow", "4"))
        self.nDinning.setItemText(4, _translate("MainWindow", "5"))
        self.nDinning.setItemText(5, _translate("MainWindow", "6"))
        self.nDinning.setItemText(6, _translate("MainWindow", "7"))
        self.nDinning.setItemText(7, _translate("MainWindow", "8"))
        self.nDinning.setItemText(8, _translate("MainWindow", "9"))
        self.nDinning.setItemText(9, _translate("MainWindow", "10"))
        self.nDinning.setItemText(10, _translate("MainWindow", "11"))
        self.nDinning.setItemText(11, _translate("MainWindow", "12"))
        self.nDinning.setItemText(12, _translate("MainWindow", "13"))
        self.nDinning.setItemText(13, _translate("MainWindow", "14"))
        self.nDinning.setItemText(14, _translate("MainWindow", "15"))
        self.nDinning.setItemText(15, _translate("MainWindow", "16"))
        self.nDinning.setItemText(16, _translate("MainWindow", "17"))
        self.nDinning.setItemText(17, _translate("MainWindow", "18"))
        self.nDinning.setItemText(18, _translate("MainWindow", "19"))
        self.nDinning.setItemText(19, _translate("MainWindow", "20"))
        self.nDinning.setItemText(20, _translate("MainWindow", "21"))
        self.nDinning.setItemText(21, _translate("MainWindow", "22"))
        self.nDinning.setItemText(22, _translate("MainWindow", "23"))
        self.nDinning.setItemText(23, _translate("MainWindow", "24"))
        self.nDinning.setItemText(24, _translate("MainWindow", "25"))
        self.nDinning.setItemText(25, _translate("MainWindow", "26"))
        self.nDinning.setItemText(26, _translate("MainWindow", "27"))
        self.nDinning.setItemText(27, _translate("MainWindow", "28"))
        self.nDinning.setItemText(28, _translate("MainWindow", "29"))
        self.nDinning.setItemText(29, _translate("MainWindow", "30"))
        self.labelForLambda1.setText(_translate("MainWindow", "Lambda 1"))
        self.labelForMaximum.setText(_translate("MainWindow", "Maximum population"))
        self.labelForNumber.setText(_translate("MainWindow", "Number"))
        self.labelForFloor.setText(_translate("MainWindow", "Floor"))
        self.labelForDinning.setText(_translate("MainWindow", "Dinning floor"))
        self.lebelForLambda2.setText(_translate("MainWindow", "Lambda 2"))
        self.labelForSpeedSlider.setText(_translate("MainWindow", "Speed"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

