# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\keypg\Documents\Coding\Python\ElevatorSimulator\views\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import importlib.util
spec = importlib.util.spec_from_file_location("GraphCanvas", "views/GraphCanvas.py")
impCanvas = importlib.util.module_from_spec(spec)
spec.loader.exec_module(impCanvas)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 841)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1100, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.gridLayout_10.addLayout(self.horizontalLayout_24, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 2, 1, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.gridLayout_10.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem1, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.simulatorFrame = QtWidgets.QFrame(self.frame)
        self.simulatorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.simulatorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.simulatorFrame.setObjectName("simulatorFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.simulatorFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.display_view = QtWidgets.QGraphicsView(self.simulatorFrame)
        self.display_view.setObjectName("display_view")
        self.gridLayout_2.addWidget(self.display_view, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.simulatorFrame, 0, 0, 1, 1)
        self.controlFrame = QtWidgets.QFrame(self.frame)
        self.controlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlFrame.setObjectName("controlFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.controlFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        self.labelClock = QtWidgets.QLabel(self.controlFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelClock.setFont(font)
        self.labelClock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClock.setObjectName("labelClock")
        self.gridLayout_3.addWidget(self.labelClock, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.controlFrame)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 2, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.labelSlider = QtWidgets.QLabel(self.controlFrame)
        self.labelSlider.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSlider.setObjectName("labelSlider")
        self.horizontalLayout_19.addWidget(self.labelSlider)
        self.slider = QtWidgets.QSlider(self.controlFrame)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout_19.addWidget(self.slider)
        self.gridLayout_3.addLayout(self.horizontalLayout_19, 3, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.startBtn = QtWidgets.QPushButton(self.controlFrame)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout_20.addWidget(self.startBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.controlFrame)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout_20.addWidget(self.pauseBtn)
        self.stopBtn = QtWidgets.QPushButton(self.controlFrame)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_20.addWidget(self.stopBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout_20, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.controlFrame, 1, 1, 1, 1)
        self.graphFrame = QtWidgets.QFrame(self.frame)
        self.graphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphFrame.setObjectName("graphFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.graphFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelPopulationTable = QtWidgets.QLabel(self.graphFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPopulationTable.setFont(font)
        self.labelPopulationTable.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPopulationTable.setObjectName("labelPopulationTable")
        self.verticalLayout_8.addWidget(self.labelPopulationTable)
        self.populationTable = QtWidgets.QTableWidget(self.graphFrame)
        self.populationTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.populationTable.sizePolicy().hasHeightForWidth())
        self.populationTable.setSizePolicy(sizePolicy)
        self.populationTable.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        self.populationTable.setFont(font)
        self.populationTable.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.populationTable.setAutoFillBackground(False)
        self.populationTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.populationTable.setTabKeyNavigation(False)
        self.populationTable.setProperty("showDropIndicator", False)
        self.populationTable.setDragDropOverwriteMode(False)
        self.populationTable.setAlternatingRowColors(True)
        self.populationTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.populationTable.setTextElideMode(QtCore.Qt.ElideNone)
        self.populationTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.populationTable.setWordWrap(False)
        self.populationTable.setObjectName("populationTable")
        self.populationTable.setColumnCount(3)
        self.populationTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.populationTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.populationTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.populationTable.setItem(1, 2, item)
        self.populationTable.horizontalHeader().setVisible(True)
        self.populationTable.horizontalHeader().setHighlightSections(True)
        self.populationTable.horizontalHeader().setStretchLastSection(True)
        self.populationTable.verticalHeader().setCascadingSectionResizes(False)
        self.populationTable.verticalHeader().setSortIndicatorShown(False)
        self.populationTable.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.populationTable)
        self.gridLayout_7.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.graphCanvas = impCanvas.GraphCanvas(self.graphFrame, width = 8, height = 8)
        self.graphCanvas.setMinimumSize(QtCore.QSize(0, 400))
        self.graphCanvas.setObjectName("graphCanvas")
        self.gridLayout_7.addWidget(self.graphCanvas, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.graphFrame, 0, 1, 1, 1)
        self.settingsFrame = QtWidgets.QFrame(self.frame)
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.settingsFrame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(52, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelNumber = QtWidgets.QLabel(self.settingsFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNumber.setFont(font)
        self.labelNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNumber.setObjectName("labelNumber")
        self.verticalLayout_3.addWidget(self.labelNumber)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelFloor = QtWidgets.QLabel(self.settingsFrame)
        self.labelFloor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFloor.setObjectName("labelFloor")
        self.verticalLayout_2.addWidget(self.labelFloor)
        self.labelElevator = QtWidgets.QLabel(self.settingsFrame)
        self.labelElevator.setAlignment(QtCore.Qt.AlignCenter)
        self.labelElevator.setObjectName("labelElevator")
        self.verticalLayout_2.addWidget(self.labelElevator)
        self.labelDinning = QtWidgets.QLabel(self.settingsFrame)
        self.labelDinning.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDinning.setObjectName("labelDinning")
        self.verticalLayout_2.addWidget(self.labelDinning)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nFloor = QtWidgets.QComboBox(self.settingsFrame)
        self.nFloor.setObjectName("nFloor")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.nFloor.addItem("")
        self.verticalLayout.addWidget(self.nFloor)
        self.nElevator = QtWidgets.QComboBox(self.settingsFrame)
        self.nElevator.setObjectName("nElevator")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.nElevator.addItem("")
        self.verticalLayout.addWidget(self.nElevator)
        self.nDinning = QtWidgets.QComboBox(self.settingsFrame)
        self.nDinning.setObjectName("nDinning")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.nDinning.addItem("")
        self.verticalLayout.addWidget(self.nDinning)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(15, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.labelAdvance = QtWidgets.QLabel(self.settingsFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAdvance.setFont(font)
        self.labelAdvance.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelAdvance.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAdvance.setObjectName("labelAdvance")
        self.verticalLayout_12.addWidget(self.labelAdvance)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.labelMaximum = QtWidgets.QLabel(self.settingsFrame)
        self.labelMaximum.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaximum.setObjectName("labelMaximum")
        self.horizontalLayout_14.addWidget(self.labelMaximum)
        self.inputMax = QtWidgets.QLineEdit(self.settingsFrame)
        self.inputMax.setAlignment(QtCore.Qt.AlignCenter)
        self.inputMax.setObjectName("inputMax")
        self.horizontalLayout_14.addWidget(self.inputMax)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.labelLambda = QtWidgets.QLabel(self.settingsFrame)
        self.labelLambda.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLambda.setObjectName("labelLambda")
        self.horizontalLayout_15.addWidget(self.labelLambda)
        self.inputLambda = QtWidgets.QLineEdit(self.settingsFrame)
        self.inputLambda.setAlignment(QtCore.Qt.AlignCenter)
        self.inputLambda.setObjectName("inputLambda")
        self.horizontalLayout_15.addWidget(self.inputLambda)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelPeakTime = QtWidgets.QLabel(self.settingsFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPeakTime.setFont(font)
        self.labelPeakTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPeakTime.setObjectName("labelPeakTime")
        self.verticalLayout_13.addWidget(self.labelPeakTime)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.labelFrom = QtWidgets.QLabel(self.settingsFrame)
        self.labelFrom.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFrom.setObjectName("labelFrom")
        self.horizontalLayout_17.addWidget(self.labelFrom)
        self.inputFrom = QtWidgets.QTimeEdit(self.settingsFrame)
        self.inputFrom.setObjectName("inputFrom")
        self.horizontalLayout_17.addWidget(self.inputFrom)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.labelTo = QtWidgets.QLabel(self.settingsFrame)
        self.labelTo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTo.setObjectName("labelTo")
        self.horizontalLayout_18.addWidget(self.labelTo)
        self.inputTo = QtWidgets.QTimeEdit(self.settingsFrame)
        self.inputTo.setObjectName("inputTo")
        self.horizontalLayout_18.addWidget(self.inputTo)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.verticalLayout_11.addLayout(self.verticalLayout_13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(52, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.settingsFrame, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout_us = QtWidgets.QAction(MainWindow)
        self.actionAbout_us.setObjectName("actionAbout_us")
        self.menuMenu.addAction(self.actionClose)
        self.menuMenu.addAction(self.actionAbout_us)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ElevatorSimulator"))
        self.labelClock.setText(_translate("MainWindow", "Time"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "7:00"))
        self.labelSlider.setText(_translate("MainWindow", "Speed : "))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.pauseBtn.setText(_translate("MainWindow", "Pause"))
        self.stopBtn.setText(_translate("MainWindow", "Stop"))
        self.labelPopulationTable.setText(_translate("MainWindow", "Population in each floor"))
        item = self.populationTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Floor"))
        item = self.populationTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Population"))
        item = self.populationTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lambda"))
        __sortingEnabled = self.populationTable.isSortingEnabled()
        self.populationTable.setSortingEnabled(False)
        item = self.populationTable.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.populationTable.item(0, 1)
        item.setText(_translate("MainWindow", "11"))
        item = self.populationTable.item(0, 2)
        item.setText(_translate("MainWindow", "4"))
        item = self.populationTable.item(1, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.populationTable.item(1, 1)
        item.setText(_translate("MainWindow", "43"))
        item = self.populationTable.item(1, 2)
        item.setText(_translate("MainWindow", "8"))
        self.populationTable.setSortingEnabled(__sortingEnabled)
        self.labelNumber.setText(_translate("MainWindow", "Number"))
        self.labelFloor.setText(_translate("MainWindow", "Floor"))
        self.labelElevator.setText(_translate("MainWindow", "Elevator"))
        self.labelDinning.setText(_translate("MainWindow", "Dinning floor "))
        self.nFloor.setItemText(0, _translate("MainWindow", "5"))
        self.nFloor.setItemText(1, _translate("MainWindow", "6"))
        self.nFloor.setItemText(2, _translate("MainWindow", "7"))
        self.nFloor.setItemText(3, _translate("MainWindow", "8"))
        self.nFloor.setItemText(4, _translate("MainWindow", "9"))
        self.nFloor.setItemText(5, _translate("MainWindow", "10"))
        self.nFloor.setItemText(6, _translate("MainWindow", "11"))
        self.nFloor.setItemText(7, _translate("MainWindow", "12"))
        self.nFloor.setItemText(8, _translate("MainWindow", "13"))
        self.nFloor.setItemText(9, _translate("MainWindow", "14"))
        self.nFloor.setItemText(10, _translate("MainWindow", "15"))
        self.nFloor.setItemText(11, _translate("MainWindow", "16"))
        self.nFloor.setItemText(12, _translate("MainWindow", "17"))
        self.nFloor.setItemText(13, _translate("MainWindow", "18"))
        self.nFloor.setItemText(14, _translate("MainWindow", "19"))
        self.nFloor.setItemText(15, _translate("MainWindow", "20"))
        self.nFloor.setItemText(16, _translate("MainWindow", "21"))
        self.nFloor.setItemText(17, _translate("MainWindow", "22"))
        self.nFloor.setItemText(18, _translate("MainWindow", "23"))
        self.nFloor.setItemText(19, _translate("MainWindow", "24"))
        self.nFloor.setItemText(20, _translate("MainWindow", "25"))
        self.nFloor.setItemText(21, _translate("MainWindow", "26"))
        self.nFloor.setItemText(22, _translate("MainWindow", "27"))
        self.nFloor.setItemText(23, _translate("MainWindow", "28"))
        self.nFloor.setItemText(24, _translate("MainWindow", "29"))
        self.nFloor.setItemText(25, _translate("MainWindow", "30"))
        self.nElevator.setItemText(0, _translate("MainWindow", "2"))
        self.nElevator.setItemText(1, _translate("MainWindow", "3"))
        self.nElevator.setItemText(2, _translate("MainWindow", "4"))
        self.nElevator.setItemText(3, _translate("MainWindow", "5"))
        self.nElevator.setItemText(4, _translate("MainWindow", "6"))
        self.nDinning.setItemText(0, _translate("MainWindow", "1"))
        self.nDinning.setItemText(1, _translate("MainWindow", "2"))
        self.nDinning.setItemText(2, _translate("MainWindow", "3"))
        self.nDinning.setItemText(3, _translate("MainWindow", "4"))
        self.nDinning.setItemText(4, _translate("MainWindow", "5"))
        self.nDinning.setItemText(5, _translate("MainWindow", "6"))
        self.nDinning.setItemText(6, _translate("MainWindow", "7"))
        self.nDinning.setItemText(7, _translate("MainWindow", "8"))
        self.nDinning.setItemText(8, _translate("MainWindow", "9"))
        self.nDinning.setItemText(9, _translate("MainWindow", "10"))
        self.nDinning.setItemText(10, _translate("MainWindow", "11"))
        self.nDinning.setItemText(11, _translate("MainWindow", "12"))
        self.nDinning.setItemText(12, _translate("MainWindow", "13"))
        self.nDinning.setItemText(13, _translate("MainWindow", "14"))
        self.nDinning.setItemText(14, _translate("MainWindow", "15"))
        self.nDinning.setItemText(15, _translate("MainWindow", "16"))
        self.nDinning.setItemText(16, _translate("MainWindow", "17"))
        self.nDinning.setItemText(17, _translate("MainWindow", "18"))
        self.nDinning.setItemText(18, _translate("MainWindow", "19"))
        self.nDinning.setItemText(19, _translate("MainWindow", "20"))
        self.nDinning.setItemText(20, _translate("MainWindow", "21"))
        self.nDinning.setItemText(21, _translate("MainWindow", "22"))
        self.nDinning.setItemText(22, _translate("MainWindow", "23"))
        self.nDinning.setItemText(23, _translate("MainWindow", "24"))
        self.nDinning.setItemText(24, _translate("MainWindow", "25"))
        self.nDinning.setItemText(25, _translate("MainWindow", "26"))
        self.nDinning.setItemText(26, _translate("MainWindow", "27"))
        self.nDinning.setItemText(27, _translate("MainWindow", "28"))
        self.nDinning.setItemText(28, _translate("MainWindow", "29"))
        self.nDinning.setItemText(29, _translate("MainWindow", "30"))
        self.labelAdvance.setText(_translate("MainWindow", "Advance settings"))
        self.labelMaximum.setText(_translate("MainWindow", "Maximum population"))
        self.inputMax.setPlaceholderText(_translate("MainWindow", "100"))
        self.labelLambda.setText(_translate("MainWindow", "Lambda Percentage"))
        self.inputLambda.setPlaceholderText(_translate("MainWindow", "30"))
        self.labelPeakTime.setText(_translate("MainWindow", "Peaktime"))
        self.labelFrom.setText(_translate("MainWindow", "From"))
        self.labelTo.setText(_translate("MainWindow", "To"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAbout_us.setText(_translate("MainWindow", "About us"))

